# 不同角色配置不同的技能连招

# 角色名字
role_name: 大枪

# 技能配置列表
# 配置说明：
#  1. skill_name表示技能的名字，time表示技能的持续时间，wait表示技能之间的间隔时间
#  2. skill_name=move时 表示移动的方法，param表示移动的方法有两个参数：角度、移动时间，使用param
#  3. skill_name=attack时 表示攻击的方法，time表示攻击次数


# buff技能配置
buff_skills:
#  - skill_name: skill_w




# 状态技能[只需要开启一次的技能]配置
state_skills:
  - skill_name: skill_right
    wait: 0.4
  - skill_name: skill_down
  # 使用默认持续时间，所以不需要time



# 觉醒技能释放配置
unique_skills:
  - skill_name: move
    param: [265, 0.4] # 移动的方法有两个参数，使用param
  - skill_name: skill_r
    time: 0.2 # 技能的持续时间 也就是按住不松开的时间
  - skill_name: skill_4


## boss房间技能配置
#boss_skills:
#  - skill_name: move
#    param: [0, 0.2]
#  - skill_name: skill_r
#    time: 0.8
room_skills:
     #第一个房间
  - - room_ij: [ 1, 0 ]
    - { skill_name: skill_f, time: 0.7 }

     #第二个房间
  - - room_ij: [ 2, 0 ]
    - { skill_name: move, param: [ 225, 0.5 ] }
    - { skill_name: move, param: [ 0, 0.1 ] }
    - { skill_name: skill_4, wait: 1.8 }

     #第三个房间 刺弹
  - - room_ij: [ 2, 1 ]
    - { skill_name: move, param: [ 330, 0.3 ] }
    - { skill_name: skill_2, wait: 1.7 }

     #第四个房间 榴弹+碉堡
  - - room_ij: [ 2, 2 ]
    - { skill_name: move, param: [ 330, 0.1 ] }
    - { skill_name: skill_f, time: 0.7 }


     #第五个房间 压缩
  - - room_ij: [ 1, 2 ]
    - { skill_name: move, param: [ 35, 0.7 ] }
    - { skill_name: move, param: [ 200, 0.1 ] }
    - { skill_name: skill_e, time: 3 }
    - { skill_name: move, param: [ 200, 1.5 ] }


     #第六个房间 激光+喷子
  - - room_ij: [ 1, 3 ]
    - { skill_name: move, param: [ 330, 0.3 ] }
    - { skill_name: skill_f, time: 1 }

     #boss前一个房间 刺弹
  - - room_ij: [ 1, 4 ]
    - { skill_name: move, param: [ 330, 0.2 ] }
    - { skill_name: move, param: [ 0, 0.1 ] }
    - { skill_name: skill_2 , wait: 1.7 }

     #boss房间
  - - room_ij: [ 1, 5 ]
    - { skill_name: skill_1, time: 0.7 }

# 伤害技能配置
hurt_skills:
    - skill_name: attack
      time: 3
    
    - skill_name: skill_3
      time: 3

